[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyMutSpec"
version = "0.0.13"
description = "Mutational spectra analysis package"
authors = [
  { name="kpotoh", email="axepon@mail.ru" },
]
license = { file = "LICENSE" }
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
classifiers = [
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "numpy<2.0",
    "pandas<2.0",
    "seaborn==0.12.2",
    "biopython>=1.75",
    "ete3>=3",
    "tqdm",
    "PyYAML",
    "pytest",
    "click",
]
# TODO incluce scripts

[project.urls]
"Homepage" = "https://github.com/mitoclub/PyMutSpec"
"Bug Tracker" = "https://github.com/mitoclub/PyMutSpec/issues"
