[tox]
minversion = 4.0
envlist = py38,py39,py310,py311,py312
isolated_build = true

[pep8]
max-line-length = 110

[testenv]
description = Run test suite with pytest
extras = dev
deps =
    pytest>=8
commands =
	pytest

[testenv:lint]
description = run linters
skip_install = true
deps =
    ruff
commands = ruff check .